### ISSUE TITLE
Octave Script to Notebook Converter

### ISSUE THREAD

**Issue by sukhjitsehra** [vatlab/sos-matlab#11]
I have octave scripts that would be converted to jupyter notebooks, it is a recurrent process. The original code would be written in the octave files and the end product would be jupyter notebooks. Therefore, the octave script to notebook converter is requested.

**Comment by BoPeng** [comment]
Please update `sos-matlab` to the latest version (which I just released) and use command `sos convert FIEL.m FILE.ipynb` for the conversion. Two options are supported.

```
sos convert m-ipynb -h
usage: sos convert FILE.m FILE.ipynb (or --to ipynb) [-h] [--kernel {octave,matlab}] [--use-sos]

Convert an Octave or Matlab .m script to Jupyter notebook (.ipynb) so that it can be opened by Jupyter notebook.

optional arguments:
  -h, --help            show this help message and exit
  --kernel {octave,matlab}
                        Kernel to use, octave or matlab, default to octave.
  --use-sos             generate a sos notebook (with octave or matlab as a subkernel), or a Notebook using Octave or Matlab kernel
                        directly.
```

Feel free to let me know if you have any additional question.

**Comment by sukhjitsehra** [comment]
Thanks @BoPeng 

I installed the latest version of sos-matlab and tried to run `sos convert test.m test.ipynb`. But converting it into a single cell only in the jupyter notebook. Is I am doing something incorrectly.

**Comment by BoPeng** [comment]
Yes because there is no way for the converter to know how you would like to separate the statements. Actually, parsing the script to separate the statements is non-trivial.

The best can be done is to find some natural way to separate the statements, such as double new line, or comment lines.

**Comment by BoPeng** [comment]
@tsara-s I will assign this project to you.
 
Basically, you will need to 

1. check out this repo.
2. Install this module locally, using `pip install -e .` when you are at the root directory of the checked-out repo. This will allow whatever changes you make to be available directly (do not need to "install" the module).
3. (optional) install vs code plus its python extension, but you can use whatever editor you are familiar with.
4. make the changes to `converter.py`
5. Test it with `sos convert test.m test.ipynb`, check the results using jupyter.
6. When you are done, create a pull request to this repository (read github documentation about PR).

**Comment by BoPeng** [comment]
@sukhjitsehra We have updated the converter to separate scripts into multiple cells if they are separated by blanks lines. It will not work every time (e.g. when you intentionally insert blank lines within statements) but should work better for you.
