### ISSUE TITLE
Two different checks for `dict` type in _Matlab_repr

### ISSUE THREAD

**Issue by ktaletsk** [vatlab/sos-matlab#4]
https://github.com/vatlab/sos-matlab/blob/847c3b74ebe863cee0234ff830383db5bd1f8737/src/sos_matlab/kernel.py#L59
https://github.com/vatlab/sos-matlab/blob/847c3b74ebe863cee0234ff830383db5bd1f8737/src/sos_matlab/kernel.py#L96

My understanding is that latter `elif` statement will never run. Which one was meant to be used?

**Comment by BoPeng** [comment]
Good question, but I do not know the answer for sure.

I think the first `elif` was trying to use native matlab `struct` and the second `elif` tried to use `scipy.io`, and I am not entirely sure which one works better for which type of input. I developed the matlab module when I had a trial version of it for a month, which has now expired so I cannot do anything now. If you have a working version of matlab, could you try to comment out one of them, feed the module with some test data and check?

**Comment by HenryLeongStat** [comment]
@ktaletsk Thanks for checking! I confirmed that `struct` should be the one meant to be used. Probably I forgot to delete those lines of `scipy.io` when I was working on the kernel. Luckily those couple lines don't hurt! :)

**Comment by BoPeng** [comment]
@HenryLeongStat Please

1. Confirm that the matlab test passes.
2. Check if the `scipy.io` approach works (by removing the first `elif` block).
3. Create some large struct (python dict) and check the robustness and performance of both approaches
4. Document the result here and remove one of the approaches.

**Comment by HenryLeongStat** [comment]
`scipy.io` approach doesn't work. The `string` approach is something I use in Ruby as well.

**Comment by BoPeng** [comment]
Please be more specific on why `scipy.io` does not work. Did it fail to save data or load data? What kind of data it accepts? Can we make it work?

**Comment by BoPeng** [comment]
It would be easier if you test this function directly and figure out the correct way to use `scipy.io`.

**Comment by HenryLeongStat** [comment]
`scipy.io` returns a struct, with a field called `obj`, which is the name of the variable inside the python kernel function. 

It means, in MATLAB, all the variable names have to add `.obj` in order to get the field out. And this problem seems very similar, I have memory about it...

I think there should be a way walk around it though... But the current approach seems stable and it is stable with other languages as well.

**Comment by HenryLeongStat** [comment]
OK... problem of scipy.io can be fixed easily thanks to reference of `https://github.com/vatlab/sos-matlab/blob/master/src/sos_matlab/sos_load_obj.m` 

I try a 10 millions rows python dict and both approaches take a forever to run. But I guess scipy.io is better than `string` just like what we did in R with feather. 

@BoPeng Professor, I will make a new branch and let you decide! :D

**Comment by BoPeng** [comment]
Why did you go with 10 millions from the beginning, start from 10 thousand and check the difference.

**Comment by HenryLeongStat** [comment]
I did try 10 thousands, even 100 thousands, they are pretty fast.

However, I just tried 1 million, scipy.io works pretty fast, and string approach fails!

**Comment by BoPeng** [comment]
ok. I will create a new release.
