### ISSUE TITLE
Missing dependency on scipy

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-matlab#5]
Right now the language module uses `scipy.io` for transfer of some datatypes. We should include `scipy` in `setup.py` so that it can be installed automatically.

**Comment by HenryLeongStat** [comment]
Which `setup.py` file? The one in `MATLAB`?

**Comment by BoPeng** [comment]
[here](https://github.com/vatlab/sos-matlab/blob/master/setup.py#L42) if `scipy` is used after #4 is resolved.

**Comment by HenryLeongStat** [comment]
It has to be used for some variables types like [here](https://github.com/vatlab/sos-matlab/blob/master/src/sos_matlab/kernel.py#L93). I suggest we should use `string` for #4 unless we have a good reason...

I will add `scipy` in `setup.py`.

**Comment by BoPeng** [comment]
Then add `scipy` as a dependency for `sos-matlab`. For #4, my biggest concern is that if user data gets large,  our approach can be slow even not possible.

**Comment by HenryLeongStat** [comment]
Yes, I see your point...
