### ISSUE TITLE
Bug: cannot %get DataFrame from Octave

### ISSUE THREAD

**Issue by ktaletsk** [vatlab/sos-matlab#7]
Consider the following DataFrame created in SoS kernel:

```
%use sos
import pandas as pd

df = pd.DataFrame({'name': ['Leonardo', 'Donatello', 'Michelangelo', 'Raphael'],
                   'mask': ['blue', 'purple', 'orange', 'red'],
                   'weapon': ['ninjatos', 'bo', 'nunchaku', 'sai']})
```

The next cell then hangs SoS kernel (or rather Octave subkernel):
```
%use octave
%get df
```

Looks like Octave can not read `name` from a csv file. Indeed, looking at .csv file produced by `df.to_csv('df2oct.csv', index=False)` we see:
```
name,mask,weapon
Leonardo,blue,ninjatos
Donatello,purple,bo
Michelangelo,orange,nunchaku
Raphael,red,sai
```
All the strings are unshielded (==unquoted).

Actually, changing this command slightly to include quoting of non-numerical values resolves the problem: `df.to_csv('df2oct.csv', index=False, quoting=csv.QUOTE_NONNUMERIC, quotechar="'")` (see [Pandas documentation](http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html) for details)

Contents of .csv after the fix:
```
'name','mask','weapon'
'Leonardo','blue','ninjatos'
'Donatello','purple','bo'
'Michelangelo','orange','nunchaku'
'Raphael','red','sai'
```

Octave import results:
```
df = dataframe with 3 rows and 3 columns
Src: df2oct.csv                         
_1         name   mask   weapon         
Nr         char   char     char         
 1    Donatello purple       bo         
 2 Michelangelo orange nunchaku         
 3      Raphael    red      sai   
```

The problem and subsequent fix does not seem to influence DataFrames with numerical data, such as this one in examples: https://github.com/vatlab/SoS/blob/master/development/docker-demo/examples/HomePage_Example_1.ipynb

**Comment by BoPeng** [comment]
Thanks. I just pushed a test for this case and released sos-matlab 0.18.2.
